spring.application.name=blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blog?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${SPRING_HTTP_PORT:8080}

api.security.token.secret=${JWT_SECRET:blablabla}