spring.application.name=blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blog?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
